# Generated by Django 5.1.15 on 2026-07-02 11:48

import apps.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=210, unique=True)),
                ('type', models.CharField(choices=[('EVENT', 'Event'), ('NEWS', 'News')], db_index=True, default='EVENT', max_length=10)),
                ('short_description', models.CharField(blank=True, max_length=400)),
                ('content', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='events/', validators=[apps.core.validators.validate_image])),
                ('event_date', models.DateField(blank=True, null=True)),
                ('published_date', models.DateField(blank=True, null=True)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-event_date', '-published_date', 'sort_order'],
            },
        ),
        migrations.CreateModel(
            name='LegalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=210, unique=True)),
                ('category', models.CharField(db_index=True, max_length=100)),
                ('document_file', models.FileField(upload_to='legal/', validators=[apps.core.validators.validate_document])),
                ('description', models.TextField(blank=True)),
                ('published_date', models.DateField(blank=True, null=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sort_order', '-published_date', 'title'],
            },
        ),
    ]
