# Generated by Django 5.1.15 on 2026-07-02 11:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('plan_type', models.CharField(choices=[('RD', 'RD Plan'), ('TERM', 'Term Plan'), ('DT', 'DT Plan'), ('SN', 'SN Plan')], db_index=True, max_length=10)),
                ('short_description', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField(blank=True)),
                ('benefits', models.JSONField(blank=True, default=list, help_text='List of benefit strings')),
                ('terms_conditions', models.TextField(blank=True)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PlanTableRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('label', models.CharField(blank=True, max_length=120)),
                ('duration_years', models.PositiveIntegerField(blank=True, null=True)),
                ('deposit_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('premium_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('maturity_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('interest_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('fund_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('surrender_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('family_protection', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('monthly_income', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_rows', to='plans.plan')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
